version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
  - package-ecosystem: gomod
    directories:
      - /plugins/github-conventions/tools
      - /plugins/go-conventions/tools
      - /plugins/go-conventions/hooks/goconv-hook
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns: ["*"]
