// Code generated by counterfeiter. DO NOT EDIT.
package auditfakes

import (
	"context"
	"sync"

	"github.com/jhoblitt/conventions-claude/plugins/github-conventions/tools/internal/audit"
)

type FakeRulesetLookup struct {
	RulesetsStub        func(context.Context, string) ([]audit.Ruleset, error)
	rulesetsMutex       sync.RWMutex
	rulesetsArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	rulesetsReturns struct {
		result1 []audit.Ruleset
		result2 error
	}
	rulesetsReturnsOnCall map[int]struct {
		result1 []audit.Ruleset
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRulesetLookup) Rulesets(arg1 context.Context, arg2 string) ([]audit.Ruleset, error) {
	fake.rulesetsMutex.Lock()
	ret, specificReturn := fake.rulesetsReturnsOnCall[len(fake.rulesetsArgsForCall)]
	fake.rulesetsArgsForCall = append(fake.rulesetsArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.RulesetsStub
	fakeReturns := fake.rulesetsReturns
	fake.recordInvocation("Rulesets", []interface{}{arg1, arg2})
	fake.rulesetsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRulesetLookup) RulesetsCallCount() int {
	fake.rulesetsMutex.RLock()
	defer fake.rulesetsMutex.RUnlock()
	return len(fake.rulesetsArgsForCall)
}

func (fake *FakeRulesetLookup) RulesetsCalls(stub func(context.Context, string) ([]audit.Ruleset, error)) {
	fake.rulesetsMutex.Lock()
	defer fake.rulesetsMutex.Unlock()
	fake.RulesetsStub = stub
}

func (fake *FakeRulesetLookup) RulesetsArgsForCall(i int) (context.Context, string) {
	fake.rulesetsMutex.RLock()
	defer fake.rulesetsMutex.RUnlock()
	argsForCall := fake.rulesetsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRulesetLookup) RulesetsReturns(result1 []audit.Ruleset, result2 error) {
	fake.rulesetsMutex.Lock()
	defer fake.rulesetsMutex.Unlock()
	fake.RulesetsStub = nil
	fake.rulesetsReturns = struct {
		result1 []audit.Ruleset
		result2 error
	}{result1, result2}
}

func (fake *FakeRulesetLookup) RulesetsReturnsOnCall(i int, result1 []audit.Ruleset, result2 error) {
	fake.rulesetsMutex.Lock()
	defer fake.rulesetsMutex.Unlock()
	fake.RulesetsStub = nil
	if fake.rulesetsReturnsOnCall == nil {
		fake.rulesetsReturnsOnCall = make(map[int]struct {
			result1 []audit.Ruleset
			result2 error
		})
	}
	fake.rulesetsReturnsOnCall[i] = struct {
		result1 []audit.Ruleset
		result2 error
	}{result1, result2}
}

func (fake *FakeRulesetLookup) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRulesetLookup) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ audit.RulesetLookup = new(FakeRulesetLookup)
